version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: ./kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
  eureka:
    build: ./eureka-service-discovery
    ports:
      - "8761:8761"
  postgres:
    build: ./postgres
    ports:
      - "5432:5432"