version: "3"

services:
  artifactory:
    build: ./artifactory
    # Login user: admin, password: password
    image: artifactory-oss
    # entrypoint: /bin/bash -c 'while true; do sleep 1; done'
    ports:
      - "8081:8081"
    volumes:
      - "./artifactory/volume:/var/opt/jfrog/artifactory"

  api-deployer:
    build: ./api-deployer
    image: api-deployer
    working_dir: "/project"
    volumes:
      - ".:/project"
    environment:
      ORG_GRADLE_PROJECT_artifactoryUrl: "http://artifactory:8081/artifactory"
      ORG_GRADLE_PROJECT_artifactoryUser: admin
      ORG_GRADLE_PROJECT_artifactoryPassword: password
      ORG_GRADLE_PROJECT_artifactoryRepo: "repo"
