version: '3.4'

x-artifactory-args: &artifactory-args
  ARTIFACTORY_URL: "http://${ARTIFACTORY_IP:-172.24.0.1}:8081/artifactory"
  ARTIFACTORY_USER: "admin"
  ARTIFACTORY_PASSWORD: "password"
  ARTIFACTORY_REPO: "repo"

services:
  accounting:
    build:
      context: ./accounting-service
      args:
        <<: *artifactory-args
    ports:
      - "8093:8093"
  laundry-management:
    build:
      context: ./laundry-management-service
      args:
        <<: *artifactory-args
    ports:
      - "8089:8089"
  order-management:
    build:
      context: ./order-management-service
      args:
        <<: *artifactory-args
    ports:
      - "8091:8091"
  tariff-management:
    build:
      context: ./tariff-management-service
      args:
        <<: *artifactory-args
    ports:
      - "8092:8092"
  taskcoordinator:
    build:
      context: ./taskcoordinator
      args:
        <<: *artifactory-args
    ports:
      - "8095:8095"
  user-management:
    build:
      context: ./user-management-service
      args:
        <<: *artifactory-args
    ports:
      - "8094:8094"