version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: ./kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_LISTENERS: LISTENER_IN_DOCKER://kafka:29092,LISTENER_OUT_DOCKER://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: LISTENER_IN_DOCKER://kafka:29092,LISTENER_OUT_DOCKER://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_IN_DOCKER:PLAINTEXT,LISTENER_OUT_DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_IN_DOCKER
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
  eureka:
    build: ./eureka-service-discovery
    ports:
      - "8761:8761"
  postgres:
    build: ./postgres
    ports:
      - "5432:5432"