spring:
  application:
    name: api-gateway-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    users:
      path: /order/**
      serviceId: order-management-service
      strip-prefix: false