spring:
  application:
    name: api-gateway-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    orders:
      path: /order/**
      serviceId: order-management-service
      strip-prefix: false
    tariffs:
        path: /tariffs/**
        serviceId: tariff-management-service
        strip-prefix: false
  ignored-patterns: /order/*/detail/*/tariff/*

tariff:
  management:
    service:
      name: tariff-management-service

order:
  management:
    service:
      name: order-management-service